version: '3.8'
services:
  flask_web: # name of the service it can be anything
    image: usman547/first_docker_image
    ports:
      - "5000:5000"
    environment:
      - OPENWEATHERMAP_API_KEY=your_key
