version: '3.8'
services:
  flask_web: # name of the service it can be anything
    image: usman547/weather-flask-app-repo  # if not available locally will fetch from dockre hub
    ports:
      - "5000:5000"
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
